### ISSUE TITLE
Equal to 5 buttons in a row will raise error

### ISSUE THREAD

**Issue by Jerry-py** [EpikHost/EpikCord.py#16]
Here in components.py
 ​            ​elif​ ​buttons​ ​>=​ ​5​: 
 ​                ​raise​ ​TooManyComponents​(​"You can only have 5 buttons per row."​)

**Comment by Jerry-py** [comment]
Should be > not >=

**Comment by TheUntraceable** [comment]
Ah, thanks for that Jerry :D
