### ISSUE TITLE
Reorganise all files

### ISSUE THREAD

**Issue by nav-github01001** [EpikHost/EpikCord.py#22]
## Description

You see, right now @TheUntraceable has reorganized the code into __init__.py and its such a mess. We need to reorganize code so that its cleaner and more faster

## The solution

Reorganise the code and prevent circular imports

## Checklist
- [ ] - Reorganise code

- [x] - You have checked that there is no issue already mentioning this feature, open or closed
- [x] - Full details of the requested feature have been provided/shown

**Comment by TheUntraceable** [comment]
I'll do this just before launch. That way it speeds up development and I don't have to spend 50% of the time I have to solve `Circular Import Errors`.
