### ISSUE TITLE
Add 'Enhanced EpikCord.py' Library

### ISSUE THREAD

**Issue by nav-github01001** [EpikHost/EpikCord.py#34]
### Note: This doesn't directly relate to this Library:

Enhanced EpikCord.py can support pagination, REPL with cmdline, and most importantly, lavalink server features (since wavelink was discontinued with discord.py)

## Checklist

- [x] - You have checked that there is no issue already mentioning this feature, open or closed
- [x] - Full details of the requested feature have been provided/shown

## Additional context
This is just optional, you may close this issue if not needed

**Comment by Jerry-py** [comment]
That's gonna take some time, I might can help on pagination but not on wavelink or voice because I have no idea how to do any of this even if I read the discord.py source its still gonna be confusing for me

**Comment by nav-github01001** [comment]
yeah ok

**Comment by TheUntraceable** [comment]
Wavelink isn't discontinued anymore.

**Comment by nav-github01001** [comment]
> 1. Yeah wavelink isn't discontinued anymore
> 2. Why an enhanced version? We can include this in the main lib

1. oh i didnt know that
2. i will include this in ext folder
