### ISSUE TITLE
Async Websockets

### ISSUE THREAD

**Issue by TheUntraceable** [EpikHost/EpikCord.py#6]
We *should* switch to Asynchronous Websockets with AIOHTTP, but the thing is I don't get how we'll use `client.login`, maybe that'll run the async version? I'm still baffled on how to do this one.

**Comment by TheUntraceable** [comment]
Working on this by the way :D

**Comment by TheUntraceable** [comment]
I can't make the `login` function which is meant to synchronous, whilst everything else being asynchronous.

**Comment by TheUntraceable** [comment]
I accidently closed this issue.

**Comment by Jerry-py** [comment]
Maybe use `asyncio.run(coro)` 

Maybe or use some other module

**Comment by Jerry-py** [comment]
`asyncio.run_until_complete` can be another option?

**Comment by TheUntraceable** [comment]
> `asyncio.get_event_loop().run_until_complete` can be another option?
> 
> I say this is probably the best option out of my responses

I'll try it, I forget I could use that and I was creating an entirely new loop just to utilise the `Loop.run_forever`

**Comment by Jerry-py** [comment]
> > `asyncio.get_event_loop().run_until_complete` can be another option?
> > 
> > I say this is probably the best option out of my responses
> 
> I'll try it, I forget I could use that and I was creating an entirely new loop just to utilise the `Loop.run_forever`

In discord.py source its an async function but can be called staticly: https://github.com/Pycord-Development/pycord/blob/master/discord/client.py#L450-L479

**Comment by Jerry-py** [comment]
https://github.com/Pycord-Development/pycord/blob/master/discord/client.py#L613-L671

Run is sync and in you can have a async function in sync function

**Comment by Jerry-py** [comment]
Probably fixed in https://github.com/EpikHost/EpikCord.py/pull/29

**Comment by TheUntraceable** [comment]
Nope. Pretty close though.

**Comment by TheUntraceable** [comment]
Fixed in the latest commit.
